main: me.rayzr522.scoreboardmenu.ScoreboardMenuPlugin
name: ${project.name}
version: ${project.version}
description: ${project.description}
website: https://github.com/Rayzr522/ScoreboardMenu
author: Rayzr522